name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  golangci_lint:
    name: Golang-CI (lint)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5 # action page: <https://github.com/actions/setup-go>
        with:
          go-version: '1.23'

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: -v --build-tags=race --timeout=5m